folders:
  train: "./data/restored/train/"
  test: "./data/restored/test/"
  model: "./model/"

networks:
  unet:
    input_channels: 1
    output_channels: 1
    base_channels: 6
    num_layers: 2
    encoder_block_type: "RRConvBlock"
    bottleneck_block_type: "RRConvBlock"
    decoder_block_type: "RRConvBlock"
    skip_connections_block_type: "RRConvBlock"
    encoder_kwargs:
      activation: "LeakyReLU"
      dropout_prob: 0.2
      num_recurrences: 1
      cbam: True
      cbam_reduction: 8
      cbam_activation: "LeakyReLU"
    bottleneck_kwargs:
      activation: "LeakyReLU"
      dropout_prob: 0.2
      num_recurrences: 2
      cbam: True
      cbam_reduction: 8
      cbam_activation: "LeakyReLU"
    decoder_kwargs:
      activation: "LeakyReLU"
      dropout_prob: 0.2
      num_recurrences: 1
      cbam: True
      cbam_reduction: 8
      cbam_activation: "LeakyReLU"
    skip_connections_kwargs:
      activation: "LeakyReLU"
      dropout_prob: 0.2
      num_recurrences: 2
      cbam: True
      cbam_reduction: 8
      cbam_activation: "LeakyReLU"
    attention_gates: True
    output_activation: "sigmoid"

manager:
  dataset_class: "CasingThicknessDataset"
  loss_class: "IoULoss"
  optimizer_class: "Adam"
  scaler_type: "robust"
  input_shape:
  - 1 # Number of channels
  - 360 # Height of the sections
  - 36 # Width of the sections
  placeholders:
  - -999.25
  - -999.0
  value_range:
  - -0.2
  - 0.2
  default_value: 0
  loss_params:
  optimizer_params:
    lr: 0.001
    weight_decay: 0.0001
  scaler_params:

train_validation:
  height_stride: 360
  width_stride: 18
  fraction: 0.2
  seed: 42
  expand: True
  augmented_ratio: 0.5

random_transformation:
  gaussian_alpha: 0.2
  salt_pepper_prob: 0.005
  salt_value: 5
  pepper_value: -5
  cutout_min: 0.2
  cutout_max: 0.5
  resize_min: 0.8
  resize_max: 1.2
  rotation_min: -30
  rotation_max: 30

predict:
  height_stride: 18
  width_stride: 18
  batch_size: 64
  expand: True

threshold: 0.5